---
- name: "(Setup: All NGINX) Upload NGINX Main Configuration File"
  copy:
    src: conf/nginx.conf
    dest: /etc/nginx/nginx.conf
  notify: "(Handler: All OSs) Reload NGINX"

- name: "(Setup: All NGINX) Upload NGINX HTTP Configuration Files"
  copy:
    src: "{{ item }}"
    dest: /etc/nginx/conf.d/
  with_fileglob:
    - "conf/http/*.conf"
  notify: "(Handler: All OSs) Reload NGINX"
