---
- name: "(Setup: Open Source NGINX) Enable Open Source NGINX Status"
  blockinfile:
    path: /etc/nginx/conf.d/stub_status.conf
    create: yes
    block: |
      server {
          listen 127.0.0.1:80;
          location /nginx_status {
              stub_status on;
              allow 127.0.0.1;
              deny all;
          }
      }
  when: type == "opensource"
  notify: "(Handler: All OSs) Reload NGINX"

- name: "(Setup: NGINX Plus) Enable NGINX Plus Status"
  blockinfile:
    path: /etc/nginx/conf.d/status.conf
    create: yes
    block: |
      server {
          listen 127.0.0.1:80;
          location /status {
              status;
              allow 127.0.0.1;
              deny all;
          }
      }
  when: type == "plus"
  notify: "(Handler: All OSs) Reload NGINX"
